[2024-06-17T11:43:55.619+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T11:43:55.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.load_process.load_regions manual__2024-06-17T11:43:39.907156+00:00 [queued]>
[2024-06-17T11:43:55.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.load_process.load_regions manual__2024-06-17T11:43:39.907156+00:00 [queued]>
[2024-06-17T11:43:55.845+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-17T11:43:55.918+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_process.load_regions> on 2024-06-17 11:43:39.907156+00:00
[2024-06-17T11:43:55.934+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1749) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T11:43:55.962+0000] {standard_task_runner.py:63} INFO - Started process 1776 to run task
[2024-06-17T11:43:55.943+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'load_process.load_regions', 'manual__2024-06-17T11:43:39.907156+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmphw2jl3hf']
[2024-06-17T11:43:55.968+0000] {standard_task_runner.py:91} INFO - Job 217: Subtask load_process.load_regions
[2024-06-17T11:43:56.038+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-17T11:43:56.241+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.load_process.load_regions manual__2024-06-17T11:43:39.907156+00:00 [running]> on host airflow-scheduler
[2024-06-17T11:43:56.893+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='load_process.load_regions' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T11:43:39.907156+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T11:43:39.907156+00:00'
[2024-06-17T11:43:56.904+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T11:43:56.907+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-06-17T11:43:56.915+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T11:43:57.435+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T11:43:58.463+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T11:43:59.219+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T11:44:01.980+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T11:44:02.628+0000] {cursor.py:1149} INFO - Number of results in first chunk: 3
[2024-06-17T11:44:03.007+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T11:44:03.819+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T11:44:04.251+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T11:44:04.255+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt.py", line 67, in load
    load_func(df=df, table_names=table)
  File "/local_module/loaders.py", line 32, in load_func
    write_pandas(
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/pandas_tools.py", line 438, in write_pandas
    copy_results = cursor.execute(copy_into_sql, _is_internal=True).fetchall()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01b5119f-0000-8bcc-0000-ec9500046922: SQL compilation error: error line 1 at position 80
invalid identifier 'TERRITORYID'
[2024-06-17T11:44:04.309+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ELT-PROJECT, task_id=load_process.load_regions, run_id=manual__2024-06-17T11:43:39.907156+00:00, execution_date=20240617T114339, start_date=20240617T114355, end_date=20240617T114404
[2024-06-17T11:44:04.414+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 217 for task load_process.load_regions (000904 (42000): 01b5119f-0000-8bcc-0000-ec9500046922: SQL compilation error: error line 1 at position 80
invalid identifier 'TERRITORYID'; 1776)
[2024-06-17T11:44:04.451+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T11:44:04.502+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T11:44:04.507+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
