[2024-06-20T06:00:59.514+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: dbt_dag.raw_order_details.run manual__2024-06-20T06:00:26.637836+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
