[2024-06-17T08:19:42.099+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T08:19:42.276+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.extract manual__2024-06-17T08:19:39.743165+00:00 [queued]>
[2024-06-17T08:19:42.314+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.extract manual__2024-06-17T08:19:39.743165+00:00 [queued]>
[2024-06-17T08:19:42.319+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-17T08:19:42.375+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2024-06-17 08:19:39.743165+00:00
[2024-06-17T08:19:42.434+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=229) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T08:19:42.449+0000] {standard_task_runner.py:63} INFO - Started process 230 to run task
[2024-06-17T08:19:42.434+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'extract', 'manual__2024-06-17T08:19:39.743165+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp5u93n61f']
[2024-06-17T08:19:42.460+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask extract
[2024-06-17T08:19:42.632+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-17T08:19:42.870+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.extract manual__2024-06-17T08:19:39.743165+00:00 [running]> on host airflow-scheduler
[2024-06-17T08:19:43.318+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T08:19:39.743165+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T08:19:39.743165+00:00'
[2024-06-17T08:19:43.324+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T08:19:43.327+0000] {logging_mixin.py:188} INFO - Hello Airflow
[2024-06-17T08:19:43.329+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T08:19:43.333+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_module/extract.py", line 4, in greeting
    return name
           ^^^^
NameError: name 'name' is not defined
[2024-06-17T08:19:43.422+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ELT-PROJECT, task_id=extract, run_id=manual__2024-06-17T08:19:39.743165+00:00, execution_date=20240617T081939, start_date=20240617T081942, end_date=20240617T081943
[2024-06-17T08:19:43.455+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task extract (name 'name' is not defined; 230)
[2024-06-17T08:19:43.496+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T08:19:43.536+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
