[2024-06-20T08:48:36.026+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T08:48:36.052+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_order_details.test manual__2024-06-20T08:41:09.652767+00:00 [queued]>
[2024-06-20T08:48:36.065+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_order_details.test manual__2024-06-20T08:41:09.652767+00:00 [queued]>
[2024-06-20T08:48:36.065+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-20T08:48:36.082+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_order_details.test> on 2024-06-20 08:41:09.652767+00:00
[2024-06-20T08:48:36.091+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3933) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T08:48:36.092+0000] {standard_task_runner.py:63} INFO - Started process 3935 to run task
[2024-06-20T08:48:36.091+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_order_details.test', 'manual__2024-06-20T08:41:09.652767+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp7sz94nce']
[2024-06-20T08:48:36.094+0000] {standard_task_runner.py:91} INFO - Job 270: Subtask transform.raw_order_details.test
[2024-06-20T08:48:36.115+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T08:48:36.157+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_order_details.test manual__2024-06-20T08:41:09.652767+00:00 [running]> on host airflow-scheduler
[2024-06-20T08:48:36.271+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_order_details.test' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T08:41:09.652767+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T08:41:09.652767+00:00'
[2024-06-20T08:48:36.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T08:48:36.288+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T08:48:36.290+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpo9cz614y from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T08:48:36.299+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T08:48:36.326+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T08:48:36.327+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T08:48:36.329+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T08:48:36.332+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmpx7io1ma3/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T08:48:36.333+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpo9cz614y', '--profiles-dir', '/tmp/tmpx7io1ma3', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpo9cz614y
[2024-06-20T08:48:36.334+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T08:48:36.336+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpo9cz614y', '--profiles-dir', '/tmp/tmpx7io1ma3', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T08:48:36.349+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T08:48:39.035+0000] {subprocess.py:94} INFO - [0m08:48:39  Running with dbt=1.8.2
[2024-06-20T08:48:39.314+0000] {subprocess.py:94} INFO - [0m08:48:39  Updating lock file in file path: /tmp/tmpo9cz614y/package-lock.yml
[2024-06-20T08:48:39.323+0000] {subprocess.py:94} INFO - [0m08:48:39  Installing dbt-labs/dbt_utils
[2024-06-20T08:48:40.107+0000] {subprocess.py:94} INFO - [0m08:48:40  Installed from version 0.8.6
[2024-06-20T08:48:40.108+0000] {subprocess.py:94} INFO - [0m08:48:40  Updated version available: 1.2.0
[2024-06-20T08:48:40.110+0000] {subprocess.py:94} INFO - [0m08:48:40
[2024-06-20T08:48:40.111+0000] {subprocess.py:94} INFO - [0m08:48:40  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T08:48:40.112+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T08:48:41.622+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T08:48:41.623+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T08:48:41.624+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_order_details', '--project-dir', '/tmp/tmpo9cz614y', '--profiles-dir', '/tmp/tmpx7io1ma3', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpo9cz614y
[2024-06-20T08:48:41.625+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T08:48:41.627+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_order_details', '--project-dir', '/tmp/tmpo9cz614y', '--profiles-dir', '/tmp/tmpx7io1ma3', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T08:48:41.641+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T08:48:43.817+0000] {subprocess.py:94} INFO - [0m08:48:43  Running with dbt=1.8.2
[2024-06-20T08:48:44.338+0000] {subprocess.py:94} INFO - [0m08:48:44  Registered adapter: snowflake=1.8.3
[2024-06-20T08:48:45.719+0000] {subprocess.py:94} INFO - [0m08:48:45  Found 20 models, 32 data tests, 11 sources, 682 macros
[2024-06-20T08:48:45.723+0000] {subprocess.py:94} INFO - [0m08:48:45
[2024-06-20T08:48:52.471+0000] {subprocess.py:94} INFO - [0m08:48:52  Concurrency: 1 threads (target='dev')
[2024-06-20T08:48:52.472+0000] {subprocess.py:94} INFO - [0m08:48:52
[2024-06-20T08:48:52.490+0000] {subprocess.py:94} INFO - [0m08:48:52  1 of 3 START test not_null_raw_order_details_ORDERDETAILID ..................... [RUN]
[2024-06-20T08:48:54.077+0000] {subprocess.py:94} INFO - [0m08:48:54  1 of 3 ERROR not_null_raw_order_details_ORDERDETAILID .......................... [[31mERROR[0m in 1.59s]
[2024-06-20T08:48:54.081+0000] {subprocess.py:94} INFO - [0m08:48:54  2 of 3 START test not_null_raw_order_details_ORDERID ........................... [RUN]
[2024-06-20T08:48:55.597+0000] {subprocess.py:94} INFO - [0m08:48:55  2 of 3 PASS not_null_raw_order_details_ORDERID ................................. [[32mPASS[0m in 1.51s]
[2024-06-20T08:48:55.602+0000] {subprocess.py:94} INFO - [0m08:48:55  3 of 3 START test not_null_raw_order_details_PRODUCTID ......................... [RUN]
[2024-06-20T08:48:57.230+0000] {subprocess.py:94} INFO - [0m08:48:57  3 of 3 PASS not_null_raw_order_details_PRODUCTID ............................... [[32mPASS[0m in 1.63s]
[2024-06-20T08:48:57.236+0000] {subprocess.py:94} INFO - [0m08:48:57
[2024-06-20T08:48:57.237+0000] {subprocess.py:94} INFO - [0m08:48:57  Finished running 3 data tests in 0 hours 0 minutes and 11.51 seconds (11.51s).
[2024-06-20T08:48:57.387+0000] {subprocess.py:94} INFO - [0m08:48:57
[2024-06-20T08:48:57.388+0000] {subprocess.py:94} INFO - [0m08:48:57  [31mCompleted with 1 error and 0 warnings:[0m
[2024-06-20T08:48:57.389+0000] {subprocess.py:94} INFO - [0m08:48:57
[2024-06-20T08:48:57.390+0000] {subprocess.py:94} INFO - [0m08:48:57    Database Error in test not_null_raw_order_details_ORDERDETAILID (models/staging/schema.yml)
[2024-06-20T08:48:57.392+0000] {subprocess.py:94} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2024-06-20T08:48:57.393+0000] {subprocess.py:94} INFO -   invalid identifier 'ORDERDETAILID'
[2024-06-20T08:48:57.396+0000] {subprocess.py:94} INFO -   compiled Code at target/run/dbt_project/models/staging/schema.yml/not_null_raw_order_details_ORDERDETAILID.sql
[2024-06-20T08:48:57.397+0000] {subprocess.py:94} INFO - [0m08:48:57
[2024-06-20T08:48:57.399+0000] {subprocess.py:94} INFO - [0m08:48:57  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
[2024-06-20T08:48:58.815+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2024-06-20T08:48:58.816+0000] {local.py:254} INFO - [0m08:48:57  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
[2024-06-20T08:48:59.065+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T08:48:59.066+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T08:48:59.073+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_order_details', extra=None)]
[2024-06-20T08:48:59.074+0000] {local.py:350} INFO - Outlets: []
[2024-06-20T08:48:59.075+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T08:48:59.099+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-06-20T08:48:59.133+0000] {local.py:184} ERROR - [0m08:48:43  Running with dbt=1.8.2
[0m08:48:44  Registered adapter: snowflake=1.8.3
[0m08:48:45  Found 20 models, 32 data tests, 11 sources, 682 macros
[0m08:48:45
[0m08:48:52  Concurrency: 1 threads (target='dev')
[0m08:48:52
[0m08:48:52  1 of 3 START test not_null_raw_order_details_ORDERDETAILID ..................... [RUN]
[0m08:48:54  1 of 3 ERROR not_null_raw_order_details_ORDERDETAILID .......................... [[31mERROR[0m in 1.59s]
[0m08:48:54  2 of 3 START test not_null_raw_order_details_ORDERID ........................... [RUN]
[0m08:48:55  2 of 3 PASS not_null_raw_order_details_ORDERID ................................. [[32mPASS[0m in 1.51s]
[0m08:48:55  3 of 3 START test not_null_raw_order_details_PRODUCTID ......................... [RUN]
[0m08:48:57  3 of 3 PASS not_null_raw_order_details_PRODUCTID ............................... [[32mPASS[0m in 1.63s]
[0m08:48:57
[0m08:48:57  Finished running 3 data tests in 0 hours 0 minutes and 11.51 seconds (11.51s).
[0m08:48:57
[0m08:48:57  [31mCompleted with 1 error and 0 warnings:[0m
[0m08:48:57
[0m08:48:57    Database Error in test not_null_raw_order_details_ORDERDETAILID (models/staging/schema.yml)
  000904 (42000): SQL compilation error: error line 12 at position 7
  invalid identifier 'ORDERDETAILID'
  compiled Code at target/run/dbt_project/models/staging/schema.yml/not_null_raw_order_details_ORDERDETAILID.sql
[0m08:48:57
[0m08:48:57  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
[2024-06-20T08:48:59.150+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T08:48:59.167+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 579, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 489, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 359, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 185, in handle_exception_subprocess
    raise AirflowException(f"dbt command failed. The command returned a non-zero exit code {result.exit_code}.")
airflow.exceptions.AirflowException: dbt command failed. The command returned a non-zero exit code 1.
[2024-06-20T08:48:59.184+0000] {taskinstance.py:225} INFO - Setting task transform.fact_order_details.run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T08:48:59.185+0000] {taskinstance.py:225} INFO - Setting task transform.fact_order_details.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T08:48:59.186+0000] {taskinstance.py:225} INFO - Setting task transform.gross_revenue_run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T08:48:59.186+0000] {taskinstance.py:225} INFO - Setting task transform.best_employee_run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T08:48:59.187+0000] {taskinstance.py:225} INFO - Setting task transform.popular_product_categories_run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T08:48:59.188+0000] {taskinstance.py:225} INFO - Setting task transform.fact_orders.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T08:48:59.189+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ELT-PROJECT, task_id=transform.raw_order_details.test, run_id=manual__2024-06-20T08:41:09.652767+00:00, execution_date=20240620T084109, start_date=20240620T084836, end_date=20240620T084859
[2024-06-20T08:48:59.210+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 270 for task transform.raw_order_details.test (dbt command failed. The command returned a non-zero exit code 1.; 3935)
[2024-06-20T08:48:59.260+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T08:48:59.300+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T08:48:59.304+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
