[2024-06-17T12:51:56.205+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T12:51:56.350+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.load_process.load_categories manual__2024-06-17T12:51:38.712440+00:00 [queued]>
[2024-06-17T12:51:56.380+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.load_process.load_categories manual__2024-06-17T12:51:38.712440+00:00 [queued]>
[2024-06-17T12:51:56.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-17T12:51:56.580+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_process.load_categories> on 2024-06-17 12:51:38.712440+00:00
[2024-06-17T12:51:56.605+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3948) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T12:51:56.618+0000] {standard_task_runner.py:63} INFO - Started process 3988 to run task
[2024-06-17T12:51:56.633+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'load_process.load_categories', 'manual__2024-06-17T12:51:38.712440+00:00', '--job-id', '410', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpnr7r32gd']
[2024-06-17T12:51:56.679+0000] {standard_task_runner.py:91} INFO - Job 410: Subtask load_process.load_categories
[2024-06-17T12:51:56.801+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-17T12:51:57.072+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.load_process.load_categories manual__2024-06-17T12:51:38.712440+00:00 [running]> on host airflow-scheduler
[2024-06-17T12:51:57.646+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='load_process.load_categories' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T12:51:38.712440+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T12:51:38.712440+00:00'
[2024-06-17T12:51:57.660+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T12:51:57.664+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-06-17T12:51:57.667+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T12:51:57.894+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T12:51:58.420+0000] {logging_mixin.py:188} INFO - Nama kolom di DataFrame: Index(['categoryID', 'categoryName', 'description', 'picture'], dtype='object')
[2024-06-17T12:51:58.858+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T12:51:59.768+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T12:52:02.684+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T12:52:03.764+0000] {cursor.py:1149} INFO - Number of results in first chunk: 4
[2024-06-17T12:52:04.201+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T12:52:04.706+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T12:52:06.046+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T12:52:06.053+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T12:52:06.060+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt.py", line 67, in load
    load_func(df=df, filename=table_name)
  File "/local_module/loaders.py", line 42, in load_func
    print(f"Done {table}")
                  ^^^^^
NameError: name 'table' is not defined. Did you mean: 'tuple'?
[2024-06-17T12:52:06.186+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ELT-PROJECT, task_id=load_process.load_categories, run_id=manual__2024-06-17T12:51:38.712440+00:00, execution_date=20240617T125138, start_date=20240617T125156, end_date=20240617T125206
[2024-06-17T12:52:06.246+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 410 for task load_process.load_categories (name 'table' is not defined; 3988)
[2024-06-17T12:52:06.314+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T12:52:06.392+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T12:52:06.413+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
