[2024-06-17T09:47:14.064+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T09:47:14.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.extract_process.extract_territories manual__2024-06-17T09:47:04.449669+00:00 [queued]>
[2024-06-17T09:47:14.459+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.extract_process.extract_territories manual__2024-06-17T09:47:04.449669+00:00 [queued]>
[2024-06-17T09:47:14.467+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-17T09:47:14.553+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_process.extract_territories> on 2024-06-17 09:47:04.449669+00:00
[2024-06-17T09:47:14.598+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1162) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T09:47:14.628+0000] {standard_task_runner.py:63} INFO - Started process 1183 to run task
[2024-06-17T09:47:14.619+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'extract_process.extract_territories', 'manual__2024-06-17T09:47:04.449669+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp3fr8g364']
[2024-06-17T09:47:14.677+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask extract_process.extract_territories
[2024-06-17T09:47:14.844+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-17T09:47:15.121+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.extract_process.extract_territories manual__2024-06-17T09:47:04.449669+00:00 [running]> on host airflow-scheduler
[2024-06-17T09:47:17.593+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='extract_process.extract_territories' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T09:47:04.449669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T09:47:04.449669+00:00'
[2024-06-17T09:47:17.598+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T09:47:17.603+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T09:47:17.604+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt.py", line 49, in extract
    dfs = extract(
          ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3267, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3256, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'name'
[2024-06-17T09:47:17.685+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ELT-PROJECT, task_id=extract_process.extract_territories, run_id=manual__2024-06-17T09:47:04.449669+00:00, execution_date=20240617T094704, start_date=20240617T094714, end_date=20240617T094717
[2024-06-17T09:47:17.733+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task extract_process.extract_territories (got an unexpected keyword argument 'name'; 1183)
[2024-06-17T09:47:17.794+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T09:47:17.863+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T09:47:17.884+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
